language: node_js
node_js:
- 8
- 9
- 10
- 11

jobs:
  include:
    - stage: test
      script: npm run test:deps
    - script: npm run test:export
    - script: npm run test:external
    - script: npm run test:jest
